name: Publish Docker image
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:

  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    # needs: [ setup ]
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        variant: 
          - "1.20"
          - "1.23"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image bullseye
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          build-args: |
            VARIANT=${{ matrix.variant }}
            DEBIAN_VERSION=bullseye
          tags: |
            ghcr.io/lopy-docker/vscode-devcontainer:go-${{ matrix.variant }}-tf-cv-bullseye

      - name: Build container image bookworm
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          build-args: |
            VARIANT=${{ matrix.variant }}
            DEBIAN_VERSION=bookworm
          tags: |
            ghcr.io/lopy-docker/vscode-devcontainer:go-${{ matrix.variant }}-tf-cv-bookworm
            ghcr.io/lopy-docker/vscode-devcontainer:go-${{ matrix.variant }}-tf-cv

            
